# Changes here will be overwritten by Copier
_commit: c84857f
_src_path: git@github.com:pupil-labs/pl-template.git
author_email: info@pupil-labs.com
author_fullname: Pupil Labs GmbH
author_username: pupil-labs
copyright_license: Proprietary
debug_module: false
project_description: Marc's repo of commonly reused things!
project_name: mar-common
publish_to_pypi: false
python_package_distribution_name: pupil-labs-mar-common
python_package_import_name: mar_common
repository_name: mar-common
repository_namespace: pupil-labs
repository_provider: github.com

